# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorditem',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorditem1', to='login_app.Record'),
        ),
    ]
