# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20171026_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='login_app.Order'),
        ),
    ]
