# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20171025_1913'),
        ('login_app', '0005_auto_20171025_2007'),
    ]

    operations = [
    ]
