# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_merge_20171026_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recs',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='recorditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='login_app.Order'),
        ),
        migrations.AddField(
            model_name='recorditem',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordItems', to='login_app.Record'),
        ),
        migrations.AddField(
            model_name='order',
            name='recorditems',
            field=models.ManyToManyField(through='login_app.RecordItem', to='login_app.Record'),
        ),
    ]
